# action.yml
name: "Docker-Compose Publish"
author: "Darryl Mendillo"
description: "Publish all docker containers in docker-compose file"
branding:
  icon: "database"
  color: "red"
inputs:
  version:
    description: "Release version (tag)"
    required: false
    default: ''
  docker_compose:
    description: "docker-compose file to build and publish images from"
    required: true
outputs:
  tag:
    description: "Tag that was published"
    value: ${{ steps.tag.outputs.semver }}
runs:
  using: "composite"
  steps:
    - id: tag
      run: |
        # if VERSION is not set, get it from git repo
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then
            VERSION=$(${{ github.action_path }}/src/version.sh)
        fi
        echo "VERSION: $VERSION"
        echo "::set-output name=semver::$(echo $VERSION)"
      shell: bash
    - id: publish
      run: ${{ github.action_path }}/src/publish.sh $VERSION ${{ inputs.docker_compose }}
      shell: bash
